# Generated by Django 4.0.2 on 2022-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_color_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(to='order.Cart'),
        ),
    ]
