# Generated by Django 4.0.3 on 2022-03-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationmanager_variationvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
        migrations.AlterField(
            model_name='variationvalue',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
